### ISSUE TITLE
Feature: User can create a day trip

### ISSUE THREAD

**Issue by kenkieu** [kenkieu/tripify#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can create a day trip at their desired location, have access to current weather, and set their budget.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

An application to easily create a plan by saving a budget and location for my next trip.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/74282257/134463755-5763f1fe-5c75-4b9b-b687-76c7e938b2c9.png)
![image](https://user-images.githubusercontent.com/74282257/134464028-ae021bbc-decd-42f3-bbf2-bd3643d7898d.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create landing page view
  - [x] Create nav with logo.
  - [x] Add input for trip type.
  - [x] Add background in CSS.
- [x] Create view for day trip form.
  - [x] Add required inputs for each field (Transport, Food, Activities, Souvenirs, Reserve).
  - [x] Add a submit button.
  - [x] Create a data model to hold information for all inputs, and current weather information.
- [x] Create view for day trip summary.
  - [x] Make a dummy entry.
  - [x] Create DOM generated entry with data from data model.
  - [x] Assign textContent to table where possible.
- [x] Create view swapping functionality.
- [x] Store data model in local storage.
- [x] Create planner nav link that directs back to planner.
  - [x] Re-render latest weather update for city.
  - [x] Assign textContent once again for Budget. 
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
