### ISSUE TITLE
Feature: User can delete entries

### ISSUE THREAD

**Issue by kenkieu** [kenkieu/tripify#11]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can delete entries that they no longer need.
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

If I decide that I do not want to go on a vacation, I can simply delete my trip.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/74282257/135204712-9ed0d712-9e01-4829-bab4-f9cbd2b83671.png)
![image](https://user-images.githubusercontent.com/74282257/135204791-4d8f69de-7600-448c-9502-eb957997115d.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add Delete Entry to the edit views for Day and Extended
- [x] Create a fixed modal to confirm if user would like to delete the entry
  - [x] If user clicks cancel, close modal
  - [x] If user clicks Delete, delete the budget entries in data model and reassign all values of spent to empty string 
  - [x] Switch view to home page, so user may create new entry afterwards if they desire
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
