### ISSUE TITLE
Feature: User can search weather

### ISSUE THREAD

**Issue by kenkieu** [kenkieu/tripify#12]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can access a view that displays the weather for any U.S. city of their choice.
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

If I plan to make a stop in a neighboring city, I can also check weather for that location although it's not my primary destination.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/74282257/135680037-02c80bb3-f1f6-4b7d-ba79-9c970e637a6f.png)
![image](https://user-images.githubusercontent.com/74282257/135679851-2e4e50c1-19f3-4166-b947-748ad2e93746.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] Create dummy entries for current and forecast weather
- [ ] Style with css to acheive desired look
- [ ] Create AJAX function that will take in a name of a city to get the current weather
- [ ] Create AJAX function that will take in a name of a city to get a 6 day forecast, and shift to remove the first item in the array
- [ ] Create the containers for the current weather and the forecast weather
- [ ] Make a function that will create a DOM tree for the current weather
- [ ] Make a function that will create a DOM tree for the forecast weather
- [ ] Append current weather to current-weather container
- [ ] Append forecast weather to forecast-weather container
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
