### ISSUE TITLE
Bug: Exceeding Call Limit (Weatherbit API)

### ISSUE THREAD

**Issue by kenkieu** [kenkieu/tripify#16]
#### Desired Behavior

> ##### The app should ...

Display a call limit reached error if the user has called the API 500 times for that day.
#### Actual Behavior

> ##### The app does this instead ...

Logs the error in the console, and does not display a "blue card". Blue cards display the weather information or errors.
#### Steps to Reproduce

> ##### To trigger the bug, you must ...

1. Call the API 501+ times in one day.
2. Open chrome dev tools to see the 429 error
## ✅ Task List

> ##### Commit checklist for tasks needed to fix the bug.

- [ ] Check for the xhr.status
- [ ] If status is 429
- [ ] Create a function to render the call limit reached error message
- [ ] Call the rendering function and prepend to the $dayTripContainer, and $extendedTripContainer inside of the xhr call.
- **Clean Up**
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile **and** desktop screen sizes for inclusion in the Pull Request.
