### ISSUE TITLE
Design Update: issue-1-create-day-trip

### ISSUE THREAD

**Issue by kenkieu** [kenkieu/tripify#3]
## ⚙️ Feature

> ##### Which feature is affected by this update?

User can view a rescaled weather summary.
## 📐 Plan

> ##### Summary of the technical approach to be taken.

Use media query to target resizing and re-placement of elements (margin on side).

## 🖼️ Wireframes

> ##### Updated wireframe(s) of what the app should look like when the updates are ready.

![image](https://user-images.githubusercontent.com/74282257/134465079-465c6e56-94e8-4106-8ddf-21cc36c5b49d.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] To be determined...
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that don't do anything.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile **and** desktop screen sizes for inclusion in the Pull Request.
