### ISSUE TITLE
Feature: User can create an extended trip

### ISSUE THREAD

**Issue by kenkieu** [kenkieu/tripify#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can create an extended trip at their desired location, have access to forecast weather, and set their budget.
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

An application to easily create a plan by saving a budget and location for my next trip.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/74282257/134613121-280fb8c3-9b20-4b62-94cb-26b5300cc03a.png)
![image](https://user-images.githubusercontent.com/74282257/134613205-3dabbd1a-33f2-4045-8279-9ace94f91c33.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Update data model to include object for extended trip.
  - [x] Edit "budget" variable name to reflect dayBudget.
- [x] Create view for extended trip form.
  - [x] Add required inputs for each field (Transport, **Lodging**, Food, Activities, Souvenirs, Reserve).
  - [x] Add a submit button.
  - [x] Create view for day trip summary.
  - [x] Make a dummy entry.
  - [x] Create DOM generated weather with data from data model.
  - [x] Assign textContent to table where possible.
- [x] Modify Planner (nav links) for day and extended
- [x] Make weather view a click on the weather div instead of a separate nav item.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
