### ISSUE TITLE
Design Update: Add Spent Data

### ISSUE THREAD

**Issue by kenkieu** [kenkieu/tripify#6]
## ⚙️ Feature

> ##### Which feature is affected by this update?

User can add to “Spent” fields and save as they progress through their trip.
## 📐 Plan

> ##### Summary of the technical approach to be taken.

Add number inputs to both day and extended summary views, and have a "save" button for the user to save that newly inserted spent data. Spent inputs will **not** be required, as the user will be saving as they progress through their trip. When a spent input is saved with a value, the number value will be replacing the input for any of the categories with values.
## 🖼️ Wireframes

> ##### Updated wireframe(s) of what the app should look like when the updates are ready.

![image](https://user-images.githubusercontent.com/74282257/134715196-3fbd26f8-a08a-4cd3-bcc4-83b467361076.png)
![image](https://user-images.githubusercontent.com/74282257/134715424-3c663aa3-2490-42fe-8aa2-b706f08ee575.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] Add inputs inside of the spent column's td elements.
- [ ] Create function that stores an object, that will hold the data from spent column, and add this object to the data model as daySpent.
- [ ] If there is a value for spent for that corresponding item's id, then use replaceWith() to replace the input with the value of spent on click of the "save" button.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that don't do anything.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile **and** desktop screen sizes for inclusion in the Pull Request.
