### ISSUE TITLE
Feature: User Can Add Spent Data

### ISSUE THREAD

**Issue by kenkieu** [kenkieu/tripify#7]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can add to “Spent” fields and save as they progress through their trip.
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.
I can add the actual amount I have spent on the various categories as I move through my trip.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/74282257/134715196-3fbd26f8-a08a-4cd3-bcc4-83b467361076.png)
![image](https://user-images.githubusercontent.com/74282257/134717914-1f709e2f-d447-44ff-911d-042f330bad5c.png)
## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create inputs in table td
- [x] Store the values of the input to data model upon submit
- [x] Replace the value of the input if one exists
- [x] Ensure functionality with nav items
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Work on the same steps for both day and extended trip
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
