### ISSUE TITLE
Feature: User can edit their entries

### ISSUE THREAD

**Issue by kenkieu** [kenkieu/tripify#9]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User will have the ability to edit edit their day trip as well as their extended trip entry.
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

If I have made a mistake when entering budget or spent information, I have the ability to correct it.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/74282257/134788924-6dea1841-3cd2-4bf2-af6a-64cae4cc776a.png)
![image](https://user-images.githubusercontent.com/74282257/134789068-cd233d5e-1621-4879-b9fa-37b782167e92.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create an editing view for day and extended, with inputs for both budget and spending.
- [x] Populate the existing summary data to the form
- [x] Edit data modal to include spent category items with empty string by default - this will ensure that no errors with undefined values display when editing without "spent" filled out.
- [x] On submit of edit 
  - [x] If the value of edit is equal to an empty string, instead of replacing the input with the value of an empty string, append the original summary input.
  - [x] If a value is exists in editing replace or keep the value on the summary page.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
